# syntax=docker/dockerfile:1

# Multi-stage build for the B2B admin service located in winrichdynamic-service/
FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy dependency manifests from the service directory
COPY winrichdynamic-service/package.json winrichdynamic-service/package-lock.json* ./
RUN npm ci

# Build the application
FROM base AS builder
WORKDIR /app

# Bring installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy service sources
COPY winrichdynamic-service/ ./

# Disable Next.js telemetry during the build
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production
ENV NEXT_BUILD_WORKERS 1
ENV TS_NODE_TRANSPILE_ONLY true

# Create a non-root user for the build process
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Change ownership of the app directory
RUN chown -R nextjs:nodejs /app
USER nextjs

# The --no-lint flag helps avoid linting during Docker builds
RUN npm run build -- --no-lint

# Production runtime image
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Create the runtime user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets and standalone output from the builder
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
RUN mkdir .next && chown nextjs:nodejs .next
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Ensure ownership is correct
RUN chown -R nextjs:nodejs /app

USER nextjs

# Railway listens on 8080
EXPOSE 8080
ENV PORT 8080
ENV HOSTNAME "0.0.0.0"

# Healthcheck hits the API health endpoint
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:8080/api/ping', res => process.exit(res.statusCode === 200 ? 0 : 1))"

# server.js is generated by `next build` when using the standalone output
CMD ["node", "server.js"]
