# syntax=docker/dockerfile:1

# Multi-stage build for the B2B admin service. Supports repositories where the
# service lives at the root *or* under ./winrichdynamic-service.
FROM node:18-alpine AS base

# Prepare the source tree so subsequent stages always see the app at /app.
FROM base AS prep
WORKDIR /app
COPY . .
RUN set -eux; \
    if [ -f package.json ] && grep -q '"name": "winrichdynamic-service"' package.json; then \
      echo "Detected winrichdynamic-service at repository root"; \
    elif [ -f winrichdynamic-service/package.json ]; then \
      echo "Detected winrichdynamic-service in subdirectory; flattening"; \
      find . -mindepth 1 -maxdepth 1 ! -name 'winrichdynamic-service' -exec rm -rf {} \;; \
      cp -R winrichdynamic-service/. .; \
      rm -rf winrichdynamic-service; \
    else \
      echo "winrichdynamic-service sources not found" >&2; \
      exit 1; \
    fi

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=prep /app/package.json /app/package-lock.json* ./
RUN npm ci

# Build the application
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=prep /app/. .

# Disable Next.js telemetry during the build
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production
ENV NEXT_BUILD_WORKERS 1
ENV TS_NODE_TRANSPILE_ONLY true

# Create a non-root user for the build process
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Change ownership of the app directory
RUN chown -R nextjs:nodejs /app
USER nextjs

# The --no-lint flag helps avoid linting during Docker builds
RUN npm run build -- --no-lint

# Production runtime image
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Install Chromium and required dependencies for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto-thai
RUN if [ -x /usr/bin/chromium-browser ]; then ln -sf /usr/bin/chromium-browser /usr/bin/chromium; elif [ -x /usr/lib/chromium/chromium ]; then ln -sf /usr/lib/chromium/chromium /usr/bin/chromium; fi

# Set Puppeteer environment variables
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Create the runtime user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets and standalone output from the builder
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
RUN mkdir .next && chown nextjs:nodejs .next
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Ensure ownership is correct
RUN chown -R nextjs:nodejs /app

USER nextjs

# Railway listens on 8080
EXPOSE 8080
ENV PORT 8080
ENV HOSTNAME "0.0.0.0"

# Healthcheck hits the API health endpoint
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:8080/api/ping', res => process.exit(res.statusCode === 200 ? 0 : 1))"

# server.js is generated by `next build` when using the standalone output
CMD ["node", "server.js"]
