import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Order from '@/models/Order';
import { verifyToken } from '@/lib/auth';
import { sendPaymentStatusChangeNotification, sendSlipVerificationRequest } from '@/app/notification/paymentNotifications';
import { generateQuotationFromOrder } from '@/services/quotationGenerator';

export async function POST(request: NextRequest) {
	try {
		await connectDB();
		const body = await request.json();
		const {
			customerName,
			customerPhone,
			items,
			shippingFee = 0,
			discount = 0,
			paymentMethod = 'cod',
			creditPaymentDueDate
		} = body;

		if (!customerName || !customerPhone || !Array.isArray(items) || items.length === 0) {
			return NextResponse.json({ error: 'ข้อมูลไม่ครบถ้วน' }, { status: 400 });
		}

		const totalAmount = items.reduce((sum: number, it: any) => sum + (it.price || 0) * (it.quantity || 0), 0);
		
		// สร้างข้อมูลออเดอร์ตามวิธีการชำระเงิน
		let orderData: any = {
			customerName,
			customerPhone,
			items,
			shippingFee,
			discount,
			totalAmount,
			paymentMethod,
		};

		// ถ้าเป็นการชำระเงินแบบ COD ให้กำหนดวันที่ครบกำหนด (3 วันหลังจากส่งสินค้า)
		if (paymentMethod === 'cod') {
			orderData.codPaymentStatus = 'pending';
			orderData.paymentConfirmationRequired = true;
		}

		// ถ้าเป็นการชำระเงินแบบเครดิต ให้กำหนดวันที่ครบกำหนด
		if (paymentMethod === 'credit' && creditPaymentDueDate) {
			orderData.creditPaymentDueDate = new Date(creditPaymentDueDate);
		}

		const order = await Order.create(orderData);

		// Generate quotation automatically for every online order
		let quotationData = null;
		try {
			const quotation = await generateQuotationFromOrder(order._id.toString(), {
				autoConvertToSalesOrder: false, // Default to manual conversion
				requireAdminApproval: true,
				conversionDelay: 0,
				customValidityDays: 7
			});

			quotationData = {
				id: quotation._id,
				number: quotation.quotationNumber,
				status: quotation.status,
				autoGenerated: quotation.autoGenerated,
				validUntil: quotation.validUntil
			};

			console.log(`Automatically generated quotation ${quotation.quotationNumber} for order ${order._id}`);
		} catch (quotationError) {
			console.error('Error generating automatic quotation:', quotationError);
			// Don't fail the order creation if quotation generation fails
		}

		// ถ้าเป็นการโอนเงิน ให้ส่งการแจ้งเตือนขออัพโหลดสลิป
		if (paymentMethod === 'transfer') {
			try {
				await sendSlipVerificationRequest(order._id.toString());
			} catch (notificationError) {
				console.error('Error sending slip verification request:', notificationError);
			}
		}

		// Return order with quotation information if generated
		const response: any = { order };
		if (quotationData) {
			response.quotation = quotationData;
		}

		return NextResponse.json(response, { status: 201 });
	} catch (error) {
		console.error('[B2B] Error creating order:', error);
		return NextResponse.json({ error: 'เกิดข้อผิดพลาดในการสร้างคำสั่งซื้อ' }, { status: 500 });
	}
}

export async function GET() {
  try {
    await connectDB();
    const orders = await Order.find({}).sort({ createdAt: -1 });
    return NextResponse.json(orders);
  } catch (error) {
    console.error('[B2B] Error fetching orders:', error);
    return NextResponse.json({ error: 'เกิดข้อผิดพลาดในการดึงคำสั่งซื้อ' }, { status: 500 });
  }
}

