import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Order from '@/models/Order';
import Quotation from '@/models/Quotation';
import { generateQuotationFromOrder, checkIfQuotationRequired, linkOrderToQuotation } from '@/services/quotationGenerator';

// POST: Generate quotation from existing order
export async function POST(request: NextRequest) {
  try {
    await connectDB();
    const body = await request.json();
    const { orderId, options = {} } = body;

    if (!orderId) {
      return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
    }

    // Find the order
    const order = await Order.findById(orderId);
    if (!order) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    // Check if quotation already exists
    if (order.generatedQuotationId) {
      const existingQuotation = await Quotation.findById(order.generatedQuotationId);
      if (existingQuotation) {
        return NextResponse.json({ 
          error: 'Quotation already exists for this order',
          quotation: {
            id: existingQuotation._id,
            number: existingQuotation.quotationNumber,
            status: existingQuotation.status
          }
        }, { status: 409 });
      }
    }

    // Generate quotation with provided options
    const quotation = await generateQuotationFromOrder(orderId, {
      autoConvertToSalesOrder: options.autoConvertToSalesOrder || false,
      requireAdminApproval: options.requireAdminApproval !== false, // Default true
      conversionDelay: options.conversionDelay || 0,
      customValidityDays: options.customValidityDays || 7
    });

    return NextResponse.json({
      success: true,
      quotation: {
        id: quotation._id,
        number: quotation.quotationNumber,
        status: quotation.status,
        autoGenerated: quotation.autoGenerated,
        validUntil: quotation.validUntil,
        totalAmount: quotation.totalAmount
      },
      order: {
        id: order._id,
        quotationStatus: 'generated',
        quotationGeneratedAt: new Date()
      }
    }, { status: 201 });

  } catch (error) {
    console.error('[Quotation Auto-Generation API] POST Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate quotation from order' },
      { status: 500 }
    );
  }
}

// GET: Check if quotation generation is required for an order
export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const url = new URL(request.url);
    const orderId = url.searchParams.get('orderId');

    if (!orderId) {
      return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
    }

    // Find the order
    const order = await Order.findById(orderId);
    if (!order) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    // Check if quotation already exists
    let existingQuotation = null;
    if (order.generatedQuotationId) {
      existingQuotation = await Quotation.findById(order.generatedQuotationId);
    }

    // Check if quotation is required
    const isQuotationRequired = await checkIfQuotationRequired(order);

    return NextResponse.json({
      orderId: order._id,
      orderStatus: order.status,
      totalAmount: order.totalAmount,
      quotationRequired: isQuotationRequired,
      existingQuotation: existingQuotation ? {
        id: existingQuotation._id,
        number: existingQuotation.quotationNumber,
        status: existingQuotation.status,
        autoGenerated: existingQuotation.autoGenerated,
        validUntil: existingQuotation.validUntil
      } : null,
      quotationStatus: order.quotationStatus,
      quotationGeneratedAt: order.quotationGeneratedAt
    });

  } catch (error) {
    console.error('[Quotation Auto-Generation API] GET Error:', error);
    return NextResponse.json(
      { error: 'Failed to check quotation generation requirements' },
      { status: 500 }
    );
  }
}

// PUT: Update quotation generation settings for an order
export async function PUT(request: NextRequest) {
  try {
    await connectDB();
    const body = await request.json();
    const { orderId, settings } = body;

    if (!orderId) {
      return NextResponse.json({ error: 'Order ID is required' }, { status: 400 });
    }

    if (!settings) {
      return NextResponse.json({ error: 'Settings are required' }, { status: 400 });
    }

    // Find the order
    const order = await Order.findById(orderId);
    if (!order) {
      return NextResponse.json({ error: 'Order not found' }, { status: 404 });
    }

    // Update order settings
    const updateData: any = {};
    
    if (settings.quotationRequired !== undefined) {
      updateData.quotationRequired = settings.quotationRequired;
    }
    
    if (settings.autoConvertToSalesOrder !== undefined) {
      updateData.autoConvertToSalesOrder = settings.autoConvertToSalesOrder;
    }

    // If quotation exists, update its conversion settings
    if (order.generatedQuotationId) {
      const quotationUpdateData: any = {};
      
      if (settings.autoConvertToSalesOrder !== undefined) {
        quotationUpdateData.autoConvertToSalesOrder = settings.autoConvertToSalesOrder;
      }
      
      if (settings.conversionSettings) {
        quotationUpdateData.conversionSettings = {
          ...settings.conversionSettings
        };
      }

      if (Object.keys(quotationUpdateData).length > 0) {
        await Quotation.findByIdAndUpdate(order.generatedQuotationId, quotationUpdateData);
      }
    }

    // Update order
    const updatedOrder = await Order.findByIdAndUpdate(
      orderId,
      updateData,
      { new: true }
    );

    return NextResponse.json({
      success: true,
      order: {
        id: updatedOrder?._id,
        quotationRequired: updatedOrder?.quotationRequired,
        autoConvertToSalesOrder: updatedOrder?.autoConvertToSalesOrder,
        quotationStatus: updatedOrder?.quotationStatus
      }
    });

  } catch (error) {
    console.error('[Quotation Auto-Generation API] PUT Error:', error);
    return NextResponse.json(
      { error: 'Failed to update quotation generation settings' },
      { status: 500 }
    );
  }
}