'use client';

import React, { useState, useEffect } from 'react';
import { Card } from '@/components/ui/Card';

interface ConversionEvent {
  type: 'order_to_quotation' | 'quotation_to_sales_order';
  timestamp: string;
  description: string;
  responsibleUser?: string;
}

interface ConversionHistoryProps {
  quotationId?: string;
  orderId?: string;
}

interface ConversionHistoryData {
  quotation?: {
    id: string;
    number: string;
    createdAt: string;
    status: string;
    autoGenerated: boolean;
  };
  sourceOrder?: {
    id: string;
    createdAt: string;
    totalAmount: number;
    status: string;
  };
  salesOrder?: {
    id: string;
    createdAt: string;
    totalAmount: number;
    status: string;
  };
  conversionEvents: ConversionEvent[];
}

export default function ConversionHistory({ quotationId, orderId }: ConversionHistoryProps) {
  const [history, setHistory] = useState<ConversionHistoryData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadHistory = async () => {
      if (!quotationId && !orderId) return;
      
      setLoading(true);
      setError(null);
      
      try {
        let url;
        if (quotationId) {
          url = `/api/quotations/${quotationId}/convert-to-sales-order`;
        } else if (orderId) {
          url = `/api/orders/${orderId}/conversion-history`;
        }
        
        if (!url) return;
        
        const res = await fetch(url);
        const data = await res.json();
        
        if (!res.ok) {
          throw new Error(data?.error || 'โหลดประวัติการแปลงไม่สำเร็จ');
        }
        
        setHistory(data);
      } catch (e: any) {
        setError(e?.message || 'เกิดข้อผิดพลาด');
      } finally {
        setLoading(false);
      }
    };
    
    loadHistory();
  }, [quotationId, orderId]);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString('th-TH', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getEventIcon = (type: string) => {
    switch (type) {
      case 'order_to_quotation':
        return '📋';
      case 'quotation_to_sales_order':
        return '📦';
      default:
        return '📄';
    }
  };

  const getEventColor = (type: string) => {
    switch (type) {
      case 'order_to_quotation':
        return 'bg-blue-100 text-blue-800';
      case 'quotation_to_sales_order':
        return 'bg-green-100 text-green-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getStatusColor = (status: string) => {
    const statusColors: Record<string, string> = {
      'pending': 'text-yellow-600',
      'generated': 'text-blue-600',
      'accepted': 'text-green-600',
      'rejected': 'text-red-600',
      'confirmed': 'text-green-600',
      'shipped': 'text-blue-600',
      'delivered': 'text-purple-600',
      'cancelled': 'text-red-600'
    };
    return statusColors[status] || 'text-gray-600';
  };

  if (loading) {
    return (
      <div className="p-6">
        <div className="animate-pulse space-y-4">
          <div className="h-4 bg-gray-200 rounded w-1/3"></div>
          <div className="h-4 bg-gray-200 rounded w-full"></div>
          <div className="h-4 bg-gray-200 rounded w-2/3"></div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6">
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {error}
        </div>
      </div>
    );
  }

  if (!history) {
    return (
      <div className="p-6">
        <div className="text-gray-500">ไม่พบข้อมูลประวัติการแปลง</div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      <h2 className="text-xl font-bold">ประวัติการแปลง</h2>
      
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {history.sourceOrder && (
          <Card className="p-4">
            <h3 className="font-semibold text-sm text-gray-600 mb-2">คำสั่งซื้อต้นทาง</h3>
            <div className="space-y-1">
              <div className="text-sm">เลขที่: #{history.sourceOrder.id.slice(-6)}</div>
              <div className="text-sm">วันที่: {formatDate(history.sourceOrder.createdAt)}</div>
              <div className="text-sm">ยอดรวม: ฿{history.sourceOrder.totalAmount.toLocaleString()}</div>
              <div className={`text-sm font-medium ${getStatusColor(history.sourceOrder.status)}`}>
                สถานะ: {history.sourceOrder.status}
              </div>
            </div>
          </Card>
        )}
        
        {history.quotation && (
          <Card className="p-4">
            <h3 className="font-semibold text-sm text-gray-600 mb-2">ใบเสนอราคา</h3>
            <div className="space-y-1">
              <div className="text-sm">เลขที่: {history.quotation.number}</div>
              <div className="text-sm">วันที่: {formatDate(history.quotation.createdAt)}</div>
              <div className="text-sm">ยอดรวม: ฿{history.quotation.totalAmount?.toLocaleString() || '0'}</div>
              <div className={`text-sm font-medium ${getStatusColor(history.quotation.status)}`}>
                สถานะ: {history.quotation.status}
              </div>
              {history.quotation.autoGenerated && (
                <div className="text-xs text-blue-600">สร้างอัตโนมัติ</div>
              )}
            </div>
          </Card>
        )}
        
        {history.salesOrder && (
          <Card className="p-4">
            <h3 className="font-semibold text-sm text-gray-600 mb-2">ใบสั่งขาย</h3>
            <div className="space-y-1">
              <div className="text-sm">เลขที่: #{history.salesOrder.id.slice(-6)}</div>
              <div className="text-sm">วันที่: {formatDate(history.salesOrder.createdAt)}</div>
              <div className="text-sm">ยอดรวม: ฿{history.salesOrder.totalAmount.toLocaleString()}</div>
              <div className={`text-sm font-medium ${getStatusColor(history.salesOrder.status)}`}>
                สถานะ: {history.salesOrder.status}
              </div>
            </div>
          </Card>
        )}
      </div>

      {/* Timeline */}
      <Card className="p-6">
        <h3 className="font-semibold mb-4">ไทม์ไลน์การแปลง</h3>
        
        {history.conversionEvents.length === 0 ? (
          <div className="text-gray-500 text-center py-4">
            ยังไม่มีกิจกรรมการแปลง
          </div>
        ) : (
          <div className="relative">
            {/* Timeline line */}
            <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gray-300"></div>
            
            <div className="space-y-6">
              {history.conversionEvents.map((event, index) => (
                <div key={index} className="relative flex items-start">
                  {/* Event dot */}
                  <div className={`absolute left-2 w-4 h-4 rounded-full border-2 border-white ${getEventColor(event.type)}`}></div>
                  
                  {/* Event content */}
                  <div className="ml-10 flex-1">
                    <div className="flex items-center mb-1">
                      <span className="text-lg mr-2">{getEventIcon(event.type)}</span>
                      <span className="font-medium">{event.description}</span>
                    </div>
                    <div className="text-sm text-gray-500">
                      {formatDate(event.timestamp)}
                      {event.responsibleUser && (
                        <span className="ml-2">
                          โดย: {event.responsibleUser}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </Card>

      {/* Additional Information */}
      <Card className="p-6">
        <h3 className="font-semibold mb-4">ข้อมูลเพิ่มเติม</h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div>
            <span className="font-medium">ระยะเวลาการแปลงทั้งหมด:</span>
            {history.conversionEvents.length > 1 && (
              <div className="mt-1">
                {(() => {
                  const start = new Date(history.conversionEvents[0].timestamp);
                  const end = new Date(history.conversionEvents[history.conversionEvents.length - 1].timestamp);
                  const diffHours = Math.abs(end.getTime() - start.getTime()) / (1000 * 60 * 60);
                  
                  if (diffHours < 1) {
                    return '< 1 ชั่วโมง';
                  } else if (diffHours < 24) {
                    return `${Math.floor(diffHours)} ชั่วโมง`;
                  } else {
                    return `${Math.floor(diffHours / 24)} วัน`;
                  }
                })()}
              </div>
            )}
          </div>
          
          <div>
            <span className="font-medium">จำนวนขั้นตอนการแปลง:</span>
            <div className="mt-1">{history.conversionEvents.length} ขั้นตอน</div>
          </div>
          
          {history.quotation?.autoGenerated && (
            <div>
              <span className="font-medium">การสร้างใบเสนอราคา:</span>
              <div className="mt-1">อัตโนมัติ</div>
            </div>
          )}
          
          {history.quotation?.autoConvertToSalesOrder && (
            <div>
              <span className="font-medium">การแปลงเป็นใบสั่งขาย:</span>
              <div className="mt-1">อัตโนมัติ</div>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}