import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Quotation from '@/models/Quotation';
import Order from '@/models/Order';
import { generateSalesOrderFromQuotation, checkAutoConversionConditions, getConversionHistory } from '@/services/salesOrderGenerator';

// POST: Convert quotation to sales order
export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    await connectDB();
    const quotationId = params.id;

    // Find the quotation
    const quotation = await Quotation.findById(quotationId);
    if (!quotation) {
      return NextResponse.json({ error: 'Quotation not found' }, { status: 404 });
    }

    // Check if quotation is in a valid state for conversion
    if (quotation.status !== 'accepted') {
      return NextResponse.json({ 
        error: 'Quotation must be accepted before converting to sales order',
        currentStatus: quotation.status
      }, { status: 400 });
    }

    // Check if already converted
    if (quotation.convertedToOrder) {
      const existingSalesOrder = await Order.findById(quotation.convertedToOrder);
      return NextResponse.json({ 
        error: 'Quotation already converted to sales order',
        salesOrder: existingSalesOrder ? {
          id: existingSalesOrder._id,
          status: existingSalesOrder.status,
          createdAt: existingSalesOrder.createdAt
        } : null
      }, { status: 409 });
    }

    // Get conversion options from request body
    const body = await request.json();
    const options = {
      requireAdminApproval: body.requireAdminApproval,
      conversionDelay: body.conversionDelay,
      customPaymentMethod: body.customPaymentMethod,
      customShippingFee: body.customShippingFee,
      notes: body.notes
    };

    // Generate sales order
    const salesOrder = await generateSalesOrderFromQuotation(quotationId, options);

    return NextResponse.json({
      success: true,
      quotation: {
        id: quotation._id,
        number: quotation.quotationNumber,
        status: quotation.status,
        salesOrderIssued: true,
        salesOrderNumber: quotation.salesOrderNumber
      },
      salesOrder: {
        id: salesOrder._id,
        customerName: salesOrder.customerName,
        totalAmount: salesOrder.totalAmount,
        status: salesOrder.status,
        createdAt: salesOrder.createdAt
      }
    }, { status: 201 });

  } catch (error) {
    console.error('[Quotation-to-Sales Order API] POST Error:', error);
    return NextResponse.json(
      { error: 'Failed to convert quotation to sales order' },
      { status: 500 }
    );
  }
}

// GET: Check conversion status and history
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    await connectDB();
    const quotationId = params.id;

    // Find the quotation
    const quotation = await Quotation.findById(quotationId);
    if (!quotation) {
      return NextResponse.json({ error: 'Quotation not found' }, { status: 404 });
    }

    // Check auto-conversion conditions
    const canAutoConvert = await checkAutoConversionConditions(quotation);

    // Get conversion history
    const conversionHistory = await getConversionHistory(quotationId);

    // Get sales order if already converted
    let salesOrder = null;
    if (quotation.convertedToOrder) {
      salesOrder = await Order.findById(quotation.convertedToOrder);
    }

    return NextResponse.json({
      quotation: {
        id: quotation._id,
        number: quotation.quotationNumber,
        status: quotation.status,
        autoGenerated: quotation.autoGenerated,
        autoConvertToSalesOrder: quotation.autoConvertToSalesOrder,
        conversionSettings: quotation.conversionSettings,
        convertedToOrder: quotation.convertedToOrder,
        salesOrderIssued: quotation.salesOrderIssued,
        salesOrderNumber: quotation.salesOrderNumber,
        salesOrderIssuedAt: quotation.salesOrderIssuedAt,
        respondedAt: quotation.respondedAt
      },
      salesOrder: salesOrder ? {
        id: salesOrder._id,
        status: salesOrder.status,
        totalAmount: salesOrder.totalAmount,
        createdAt: salesOrder.createdAt
      } : null,
      canAutoConvert,
      conversionHistory
    });

  } catch (error) {
    console.error('[Quotation-to-Sales Order API] GET Error:', error);
    return NextResponse.json(
      { error: 'Failed to get conversion status' },
      { status: 500 }
    );
  }
}

// PUT: Update conversion settings
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    await connectDB();
    const quotationId = params.id;
    const body = await request.json();
    const { conversionSettings } = body;

    if (!conversionSettings) {
      return NextResponse.json({ error: 'Conversion settings are required' }, { status: 400 });
    }

    // Find the quotation
    const quotation = await Quotation.findById(quotationId);
    if (!quotation) {
      return NextResponse.json({ error: 'Quotation not found' }, { status: 404 });
    }

    // Check if already converted
    if (quotation.convertedToOrder) {
      return NextResponse.json({ 
        error: 'Cannot update conversion settings for already converted quotation' 
      }, { status: 400 });
    }

    // Update conversion settings
    const updateData: any = {
      conversionSettings: {
        autoConvertOnAcceptance: conversionSettings.autoConvertOnAcceptance !== false,
        requireAdminApproval: conversionSettings.requireAdminApproval !== false,
        conversionDelay: conversionSettings.conversionDelay || 0
      }
    };

    if (conversionSettings.autoConvertToSalesOrder !== undefined) {
      updateData.autoConvertToSalesOrder = conversionSettings.autoConvertToSalesOrder;
    }

    const updatedQuotation = await Quotation.findByIdAndUpdate(
      quotationId,
      updateData,
      { new: true }
    );

    // Check if order exists and update its settings
    if (quotation.sourceOrderId) {
      await Order.findByIdAndUpdate(quotation.sourceOrderId, {
        autoConvertToSalesOrder: conversionSettings.autoConvertToSalesOrder || false
      });
    }

    return NextResponse.json({
      success: true,
      quotation: {
        id: updatedQuotation._id,
        number: updatedQuotation.quotationNumber,
        autoConvertToSalesOrder: updatedQuotation.autoConvertToSalesOrder,
        conversionSettings: updatedQuotation.conversionSettings
      }
    });

  } catch (error) {
    console.error('[Quotation-to-Sales Order API] PUT Error:', error);
    return NextResponse.json(
      { error: 'Failed to update conversion settings' },
      { status: 500 }
    );
  }
}